Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('Original:', my_data, 'Median: %1.1f' % np.median(my_data))

theta_hat_stars = []  # list to store the results
for i in range(500):   # loop over the number of replications
    resample = choices(my_data_list, k=len(my_data)) # resample the data
    print('Resample:', resample, 'Median: %1.1f' % np.median(resample))
    theta_hat_star = median(resample) # compute the statistic
    theta_hat_stars.append(theta_hat_star)      # store the result

# Create a histogram
plt.hist(theta_hat_stars, bins=20, edgecolor='black')

# Show the plot
plt.show()
------------------

----- stdout -----
Original: [19, 17, 5, 20, 14, 7, 3, 12, 6, 1, 8, 15, 16, 13, 10] Median: 12.0
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 5[0m
[1;32m      3[0m theta_hat_stars [38;5;241m=[39m []  [38;5;66;03m# list to store the results[39;00m
[1;32m      4[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m500[39m):   [38;5;66;03m# loop over the number of replications[39;00m
[0;32m----> 5[0m     resample [38;5;241m=[39m choices(my_data_list, k[38;5;241m=[39m[38;5;28mlen[39m(my_data)) [38;5;66;03m# resample the data[39;00m
[1;32m      6[0m     [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mResample:[39m[38;5;124m'[39m, resample, [38;5;124m'[39m[38;5;124mMedian: [39m[38;5;132;01m%1.1f[39;00m[38;5;124m'[39m [38;5;241m%[39m np[38;5;241m.[39mmedian(resample))
[1;32m      7[0m     theta_hat_star [38;5;241m=[39m median(resample) [38;5;66;03m# compute the statistic[39;00m

[0;31mNameError[0m: name 'my_data_list' is not defined

