Traceback (most recent call last):
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
royall_three(20, 0.5, 6)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [43mroyall_three[49m[43m([49m[38;5;241;43m20[39;49m[43m,[49m[43m [49m[38;5;241;43m0.5[39;49m[43m,[49m[43m [49m[38;5;241;43m6[39;49m[43m)[49m

Cell [0;32mIn[2], line 12[0m, in [0;36mroyall_three[0;34m(n, p, m)[0m
[1;32m      9[0m Ypdf [38;5;241m=[39m [[38;5;241m1[39m[38;5;241m-[39mXpdf[m], Xpdf[m]]
[1;32m     11[0m w [38;5;241m=[39m np[38;5;241m.[39marange([38;5;241m0[39m,[38;5;241m100[39m)  [38;5;66;03m# x-axis values[39;00m
[0;32m---> 12[0m Zpdf [38;5;241m=[39m [[43mcomb[49m(z[38;5;241m-[39m[38;5;241m1[39m, m)[38;5;241m*[39m(p[38;5;241m*[39m[38;5;241m*[39mm)[38;5;241m*[39m(([38;5;241m1[39m[38;5;241m-[39mp)[38;5;241m*[39m[38;5;241m*[39m(z[38;5;241m-[39mm)) [38;5;28;01mif[39;00m z [38;5;241m>[39m[38;5;241m=[39m m [38;5;28;01melse[39;00m [38;5;241m0[39m [38;5;28;01mfor[39;00m z [38;5;129;01min[39;00m w]
[1;32m     14[0m fig, axs [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m, [38;5;241m3[39m, figsize[38;5;241m=[39m([38;5;241m11[39m, [38;5;241m5[39m))  [38;5;66;03m# 1 row, 2 columns[39;00m
[1;32m     16[0m [38;5;66;03m# Plot of first pdf[39;00m

[0;31mNameError[0m: name 'comb' is not defined

